version: "3.0"
services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Aigh5Oir

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ebeeph2Y
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Aigh5Oir

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db

volumes:
  mariadb:
  wordpress:

